// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_menu_api_v1_stores__store_id__menu_imports_upload_post
 */
export type BodyUploadMenuApiV1StoresStoreIdMenuImportsUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BusinessDayHours
 */
export type BusinessDayHours = {
    /**
     * Status
     */
    status: 'open24' | 'closed' | 'ranges';
    /**
     * Ranges
     */
    ranges?: Array<BusinessHourRange> | null;
};

/**
 * BusinessHourRange
 */
export type BusinessHourRange = {
    /**
     * Start Min
     */
    startMin: number;
    /**
     * End Min
     */
    endMin: number;
};

/**
 * BusinessHours
 */
export type BusinessHoursInput = {
    sun: BusinessDayHours;
    mon: BusinessDayHours;
    tue: BusinessDayHours;
    wed: BusinessDayHours;
    thu: BusinessDayHours;
    fri: BusinessDayHours;
    sat: BusinessDayHours;
};

/**
 * BusinessHours
 */
export type BusinessHoursOutput = {
    sun: BusinessDayHours;
    mon: BusinessDayHours;
    tue: BusinessDayHours;
    wed: BusinessDayHours;
    thu: BusinessDayHours;
    fri: BusinessDayHours;
    sat: BusinessDayHours;
};

/**
 * CategoriesPageResponse
 */
export type CategoriesPageResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    pageSize: number;
    /**
     * Page Count
     */
    pageCount: number;
    /**
     * Items
     */
    items: Array<CategoryResponse>;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Sort Order
     */
    sortOrder?: number;
    /**
     * Is Active
     */
    isActive?: boolean;
};

/**
 * CategoryResponse
 */
export type CategoryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | undefined;
    /**
     * Sort Order
     */
    sortOrder: number;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Sort Order
     */
    sortOrder?: number | null;
    /**
     * Is Active
     */
    isActive?: boolean | null;
};

/**
 * CreateMenuImportFromUploadRequest
 */
export type CreateMenuImportFromUploadRequest = {
    /**
     * Upload Id
     */
    uploadId: string;
};

/**
 * CreatePaymentIntentRequest
 */
export type CreatePaymentIntentRequest = {
    /**
     * Order Id
     */
    orderId: string;
};

/**
 * FileType
 */
export type FileType = 'pdf' | 'image' | 'csv' | 'xlsx';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportItemStatus
 */
export type ImportItemStatus = 'pending' | 'approved' | 'edited' | 'rejected';

/**
 * ImportStatus
 */
export type ImportStatus = 'uploading' | 'processing' | 'review' | 'published' | 'failed';

/**
 * InviteStatus
 */
export type InviteStatus = 'pending' | 'accepted' | 'revoked' | 'expired';

/**
 * MemberRole
 */
export type MemberRole = 'owner' | 'admin' | 'staff';

/**
 * MenuImportItemBatchUpdate
 */
export type MenuImportItemBatchUpdate = {
    /**
     * Item Id
     */
    itemId: string;
    /**
     * Category Name
     */
    categoryName?: string | null;
    /**
     * Item Name
     */
    itemName?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Unit Amount
     */
    unitAmount?: number | null;
    /**
     * Option Lists
     */
    optionLists?: {
        [key: string]: unknown;
    } | null;
    /**
     * Dietary Tags
     */
    dietaryTags?: Array<unknown> | null;
    /**
     * Allergens
     */
    allergens?: Array<unknown> | null;
    status?: ImportItemStatus | null;
};

/**
 * MenuImportItemResponse
 */
export type MenuImportItemResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Menu Import Id
     */
    menuImportId: string;
    /**
     * Category Name
     */
    categoryName: string | null;
    /**
     * Item Name
     */
    itemName: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Unit Amount
     */
    unitAmount: number | null;
    /**
     * Option Lists
     */
    optionLists: {
        [key: string]: unknown;
    } | null;
    /**
     * Dietary Tags
     */
    dietaryTags: Array<unknown> | null;
    /**
     * Allergens
     */
    allergens: Array<unknown> | null;
    /**
     * Confidence
     */
    confidence: number;
    status: ImportItemStatus;
    /**
     * Linked Product Id
     */
    linkedProductId: string | null;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * MenuImportItemUpdate
 */
export type MenuImportItemUpdate = {
    /**
     * Category Name
     */
    categoryName?: string | null;
    /**
     * Item Name
     */
    itemName?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Unit Amount
     */
    unitAmount?: number | null;
    /**
     * Option Lists
     */
    optionLists?: {
        [key: string]: unknown;
    } | null;
    /**
     * Dietary Tags
     */
    dietaryTags?: Array<unknown> | null;
    /**
     * Allergens
     */
    allergens?: Array<unknown> | null;
    status?: ImportItemStatus | null;
};

/**
 * MenuImportItemsBatchUpdateRequest
 */
export type MenuImportItemsBatchUpdateRequest = {
    /**
     * Items
     */
    items: Array<MenuImportItemBatchUpdate>;
};

/**
 * MenuImportResponse
 */
export type MenuImportResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Uploaded By
     */
    uploadedBy: string;
    /**
     * File Url
     */
    fileUrl: string;
    /**
     * File Size Bytes
     */
    fileSizeBytes: number | null;
    /**
     * File Size Mb
     */
    fileSizeMb: number | null;
    fileType: FileType;
    status: ImportStatus;
    /**
     * Raw Extraction
     */
    rawExtraction: {
        [key: string]: unknown;
    } | null;
    /**
     * Parsed Data
     */
    parsedData: {
        [key: string]: unknown;
    } | null;
    /**
     * Confidence Scores
     */
    confidenceScores: {
        [key: string]: unknown;
    } | null;
    /**
     * Error Log
     */
    errorLog: string | null;
    /**
     * Processing Started At
     */
    processingStartedAt: string | null;
    /**
     * Ingested At
     */
    ingestedAt: string | null;
    /**
     * Ingest Duration Seconds
     */
    ingestDurationSeconds: number | null;
    /**
     * Processing Elapsed Seconds
     */
    processingElapsedSeconds: number | null;
    /**
     * Ai Processing Seconds
     */
    aiProcessingSeconds: number | null;
    /**
     * Ai Seconds Per Mb
     */
    aiSecondsPerMb: number | null;
    /**
     * Ai Mb Per Second
     */
    aiMbPerSecond: number | null;
    /**
     * Published At
     */
    publishedAt: string | null;
    /**
     * Items
     */
    items?: Array<MenuImportItemResponse>;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * OnboardingStepStatus
 */
export type OnboardingStepStatus = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Blocking Reasons
     */
    blockingReasons?: Array<string>;
};

/**
 * OptionCreate
 */
export type OptionCreate = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Unit Amount
     */
    unitAmount?: number;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Decimal Places
     */
    decimalPlaces?: number;
    /**
     * Min Option Choice Quantity
     */
    minOptionChoiceQuantity?: number;
    /**
     * Max Option Choice Quantity
     */
    maxOptionChoiceQuantity?: number;
    /**
     * Default Quantity
     */
    defaultQuantity?: number;
    /**
     * Is Default
     */
    isDefault?: boolean;
    /**
     * Sort Order
     */
    sortOrder?: number;
};

/**
 * OptionListCreate
 */
export type OptionListCreate = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Selection Node
     */
    selectionNode?: string;
    /**
     * Min Num Options
     */
    minNumOptions?: number;
    /**
     * Max Num Options
     */
    maxNumOptions?: number;
    /**
     * Min Aggregate Options Quantity
     */
    minAggregateOptionsQuantity?: number;
    /**
     * Max Aggregate Options Quantity
     */
    maxAggregateOptionsQuantity?: number;
    /**
     * Is Optional
     */
    isOptional?: boolean;
    /**
     * Sort Order
     */
    sortOrder?: number;
    /**
     * Options
     */
    options?: Array<OptionCreate>;
};

/**
 * OptionListResponse
 */
export type OptionListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    productId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Selection Node
     */
    selectionNode: string;
    /**
     * Min Num Options
     */
    minNumOptions: number;
    /**
     * Max Num Options
     */
    maxNumOptions: number;
    /**
     * Min Aggregate Options Quantity
     */
    minAggregateOptionsQuantity: number;
    /**
     * Max Aggregate Options Quantity
     */
    maxAggregateOptionsQuantity: number;
    /**
     * Is Optional
     */
    isOptional: boolean;
    /**
     * Sort Order
     */
    sortOrder: number;
    /**
     * Options
     */
    options?: Array<OptionResponse>;
};

/**
 * OptionResponse
 */
export type OptionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Option List Id
     */
    optionListId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Decimal Places
     */
    decimalPlaces: number;
    /**
     * Min Option Choice Quantity
     */
    minOptionChoiceQuantity: number;
    /**
     * Max Option Choice Quantity
     */
    maxOptionChoiceQuantity: number;
    /**
     * Default Quantity
     */
    defaultQuantity: number;
    /**
     * Is Default
     */
    isDefault: boolean;
    /**
     * Sort Order
     */
    sortOrder: number;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    /**
     * Customer Name
     */
    customerName?: string | null;
    /**
     * Customer Email
     */
    customerEmail?: string | null;
    /**
     * Customer Phone
     */
    customerPhone?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Items
     */
    items: Array<OrderItemCreate>;
};

/**
 * OrderItemCreate
 */
export type OrderItemCreate = {
    /**
     * Product Id
     */
    productId: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Options
     */
    options?: Array<OrderItemOptionCreate>;
};

/**
 * OrderItemOptionCreate
 */
export type OrderItemOptionCreate = {
    /**
     * Option Id
     */
    optionId: string;
    /**
     * Quantity
     */
    quantity?: number;
};

/**
 * OrderItemOptionResponse
 */
export type OrderItemOptionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Option Id
     */
    optionId: string | null;
    /**
     * Option Name
     */
    optionName: string;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * OrderItemResponse
 */
export type OrderItemResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    productId: string | null;
    /**
     * Product Name
     */
    productName: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Total Amount
     */
    totalAmount: number;
    /**
     * Options
     */
    options?: Array<OrderItemOptionResponse>;
};

/**
 * OrderLookupRequest
 */
export type OrderLookupRequest = {
    /**
     * Order Identifier
     */
    orderIdentifier: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * OrderLookupResponse
 */
export type OrderLookupResponse = {
    /**
     * Order Id
     */
    orderId: string;
    /**
     * Order Access Token
     */
    orderAccessToken: string;
};

/**
 * OrderResponse
 */
export type OrderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Customer Id
     */
    customerId: string | null;
    status: OrderStatus;
    /**
     * Subtotal Amount
     */
    subtotalAmount: number;
    /**
     * Tax Amount
     */
    taxAmount: number;
    /**
     * Total Amount
     */
    totalAmount: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Decimal Places
     */
    decimalPlaces: number;
    /**
     * Stripe Payment Intent Id
     */
    stripePaymentIntentId: string | null;
    /**
     * Customer Name
     */
    customerName: string | null;
    /**
     * Customer Email
     */
    customerEmail: string | null;
    /**
     * Customer Phone
     */
    customerPhone: string | null;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Order Access Token
     */
    orderAccessToken?: string | null;
    /**
     * Display Id
     */
    displayId: string;
    /**
     * Order Reference
     */
    orderReference: string;
    /**
     * Daily Sequence
     */
    dailySequence: number;
    /**
     * Items
     */
    items?: Array<OrderItemResponse>;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * OrderStatus
 */
export type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled';

/**
 * OrderStatusUpdate
 */
export type OrderStatusUpdate = {
    status: OrderStatus;
};

/**
 * OrdersPageResponse
 */
export type OrdersPageResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    pageSize: number;
    /**
     * Page Count
     */
    pageCount: number;
    /**
     * Items
     */
    items: Array<OrderResponse>;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Category Id
     */
    categoryId?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Decimal Places
     */
    decimalPlaces?: number;
    /**
     * Image Url
     */
    imageUrl?: string | null;
    /**
     * Is Active
     */
    isActive?: boolean;
    /**
     * Sort Order
     */
    sortOrder?: number;
    /**
     * Dietary Tags
     */
    dietaryTags?: Array<string>;
    /**
     * Allergens
     */
    allergens?: Array<string>;
    /**
     * Ingredients
     */
    ingredients?: string | null;
    /**
     * Option Lists
     */
    optionLists?: Array<OptionListCreate>;
};

/**
 * ProductListItemCategoryResponse
 */
export type ProductListItemCategoryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ProductResponse
 */
export type ProductResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Category Id
     */
    categoryId: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Decimal Places
     */
    decimalPlaces: number;
    /**
     * Image Url
     */
    imageUrl: string | null;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Sort Order
     */
    sortOrder: number;
    /**
     * Dietary Tags
     */
    dietaryTags: Array<string> | null;
    /**
     * Allergens
     */
    allergens: Array<string> | null;
    /**
     * Ingredients
     */
    ingredients: string | null;
    /**
     * Option Lists
     */
    optionLists?: Array<OptionListResponse>;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Category Id
     */
    categoryId?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Unit Amount
     */
    unitAmount?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Decimal Places
     */
    decimalPlaces?: number | null;
    /**
     * Image Url
     */
    imageUrl?: string | null;
    /**
     * Is Active
     */
    isActive?: boolean | null;
    /**
     * Sort Order
     */
    sortOrder?: number | null;
    /**
     * Dietary Tags
     */
    dietaryTags?: Array<string> | null;
    /**
     * Allergens
     */
    allergens?: Array<string> | null;
    /**
     * Ingredients
     */
    ingredients?: string | null;
    /**
     * Option Lists
     */
    optionLists?: Array<OptionListCreate> | null;
};

/**
 * ProductWithCategoryListItemResponse
 */
export type ProductWithCategoryListItemResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Category Id
     */
    categoryId: string | undefined;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | undefined;
    /**
     * Unit Amount
     */
    unitAmount: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Decimal Places
     */
    decimalPlaces: number;
    /**
     * Image Url
     */
    imageUrl: string | null;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Sort Order
     */
    sortOrder: number;
    /**
     * Dietary Tags
     */
    dietaryTags: Array<string> | null;
    /**
     * Allergens
     */
    allergens: Array<string> | null;
    /**
     * Ingredients
     */
    ingredients: string | null;
    /**
     * Option Lists
     */
    optionLists?: Array<OptionListResponse>;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
    category?: ProductListItemCategoryResponse | null;
};

/**
 * ProductsPageResponse
 */
export type ProductsPageResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    pageSize: number;
    /**
     * Page Count
     */
    pageCount: number;
    /**
     * Items
     */
    items: Array<ProductWithCategoryListItemResponse>;
};

/**
 * StoreCreate
 */
export type StoreCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Timezone
     */
    timezone?: string;
    businessHours?: BusinessHoursInput | null;
};

/**
 * StoreOnboardingStatusResponse
 */
export type StoreOnboardingStatusResponse = {
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Onboarding Complete
     */
    onboardingComplete: boolean;
    /**
     * Can Go Live
     */
    canGoLive: boolean;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Completed Required Steps
     */
    completedRequiredSteps: number;
    /**
     * Total Required Steps
     */
    totalRequiredSteps: number;
    /**
     * Next Step Id
     */
    nextStepId: string | null;
    /**
     * Active Product Count
     */
    activeProductCount: number;
    /**
     * Has Published Import
     */
    hasPublishedImport: boolean;
    /**
     * Steps
     */
    steps: Array<OnboardingStepStatus>;
};

/**
 * StorePublicResponse
 */
export type StorePublicResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Logo Url
     */
    logoUrl: string | null;
    /**
     * Banner Url
     */
    bannerUrl: string | null;
    /**
     * Theme Config
     */
    themeConfig: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Address
     */
    address: string | null;
    /**
     * Phone
     */
    phone: string | null;
    businessHours: BusinessHoursOutput | null;
    /**
     * Timezone
     */
    timezone: string | null;
};

/**
 * StoreResponse
 */
export type StoreResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    ownerId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Logo Url
     */
    logoUrl: string | null;
    /**
     * Banner Url
     */
    bannerUrl: string | null;
    /**
     * Theme Config
     */
    themeConfig: {
        [key: string]: unknown;
    } | null;
    /**
     * Stripe Account Id
     */
    stripeAccountId: string | null;
    /**
     * Stripe Onboarding Complete
     */
    stripeOnboardingComplete: boolean;
    /**
     * Is Active
     */
    isActive: boolean;
    /**
     * Address
     */
    address: string | null;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Timezone
     */
    timezone: string;
    businessHours: BusinessHoursOutput | null;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * StoreUpdate
 */
export type StoreUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Logo Url
     */
    logoUrl?: string | null;
    /**
     * Banner Url
     */
    bannerUrl?: string | null;
    /**
     * Theme Config
     */
    themeConfig?: {
        [key: string]: unknown;
    } | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Timezone
     */
    timezone?: string | null;
    /**
     * Is Active
     */
    isActive?: boolean | null;
    businessHours?: BusinessHoursInput | null;
};

/**
 * TeamInviteAcceptResponse
 */
export type TeamInviteAcceptResponse = {
    /**
     * Store Id
     */
    storeId: string;
    role: MemberRole;
    /**
     * Status
     */
    status: string;
};

/**
 * TeamInviteCreate
 */
export type TeamInviteCreate = {
    /**
     * Invited Email
     */
    invitedEmail: string;
    role?: MemberRole;
};

/**
 * TeamInviteResponse
 */
export type TeamInviteResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Invited By User Id
     */
    invitedByUserId: string;
    /**
     * Invited Email
     */
    invitedEmail: string;
    role: MemberRole;
    status: InviteStatus;
    /**
     * Token
     */
    token: string;
    /**
     * Invite Link
     */
    inviteLink?: string;
    /**
     * Expires At
     */
    expiresAt: string;
    /**
     * Accepted At
     */
    acceptedAt: string | null;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * TeamMemberResponse
 */
export type TeamMemberResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * User Id
     */
    userId: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    role: MemberRole;
    /**
     * Role Name
     */
    roleName: string;
    /**
     * Role Priority
     */
    rolePriority: number;
    /**
     * Permissions
     */
    permissions?: Array<string>;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * TeamMemberRoleBulkApplyRequest
 */
export type TeamMemberRoleBulkApplyRequest = {
    /**
     * Updates
     */
    updates?: Array<TeamMemberRoleBulkItem>;
};

/**
 * TeamMemberRoleBulkApplyResponse
 */
export type TeamMemberRoleBulkApplyResponse = {
    /**
     * Applied Count
     */
    appliedCount: number;
};

/**
 * TeamMemberRoleBulkItem
 */
export type TeamMemberRoleBulkItem = {
    /**
     * Member Id
     */
    memberId: string;
    /**
     * Role Id
     */
    roleId: string;
};

/**
 * TeamMemberRoleUpdate
 */
export type TeamMemberRoleUpdate = {
    /**
     * Role Id
     */
    roleId: string;
};

/**
 * TeamRoleCreate
 */
export type TeamRoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Priority
     */
    priority: number;
    /**
     * Permissions
     */
    permissions?: Array<string>;
};

/**
 * TeamRoleResponse
 */
export type TeamRoleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Store Id
     */
    storeId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Priority
     */
    priority: number;
    /**
     * Permissions
     */
    permissions?: Array<string>;
    /**
     * Is System
     */
    isSystem: boolean;
    /**
     * Is Editable
     */
    isEditable: boolean;
    /**
     * Created At
     */
    createdAt: string;
    /**
     * Updated At
     */
    updatedAt: string;
};

/**
 * TeamRoleUpdate
 */
export type TeamRoleUpdate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Priority
     */
    priority?: number | null;
    /**
     * Permissions
     */
    permissions?: Array<string> | null;
};

/**
 * UploadAssetStatus
 */
export type UploadAssetStatus = 'initiated' | 'uploaded' | 'finalized' | 'expired' | 'failed';

/**
 * UploadCompleteResponse
 */
export type UploadCompleteResponse = {
    /**
     * Upload Id
     */
    uploadId: string;
    status: UploadAssetStatus;
    /**
     * Size Bytes
     */
    sizeBytes?: number | null;
    /**
     * File Url
     */
    fileUrl: string;
};

/**
 * UploadIntent
 */
export type UploadIntent = 'menu_import_file' | 'product_image';

/**
 * UploadIntentCreate
 */
export type UploadIntentCreate = {
    intent: UploadIntent;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    contentType: string;
    /**
     * Size Bytes
     */
    sizeBytes?: number | null;
};

/**
 * UploadIntentResponse
 */
export type UploadIntentResponse = {
    /**
     * Upload Id
     */
    uploadId: string;
    /**
     * Upload Url
     */
    uploadUrl: string;
    /**
     * Object Key
     */
    objectKey: string;
    /**
     * File Url
     */
    fileUrl: string;
    /**
     * Expires In
     */
    expiresIn: number;
    status: UploadAssetStatus;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListStoresApiV1StoresGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/stores';
};

export type ListStoresApiV1StoresGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStoresApiV1StoresGetError = ListStoresApiV1StoresGetErrors[keyof ListStoresApiV1StoresGetErrors];

export type ListStoresApiV1StoresGetResponses = {
    /**
     * Response List Stores Api V1 Stores Get
     *
     * Successful Response
     */
    200: Array<StoreResponse>;
};

export type ListStoresApiV1StoresGetResponse = ListStoresApiV1StoresGetResponses[keyof ListStoresApiV1StoresGetResponses];

export type CreateStoreApiV1StoresPostData = {
    body: StoreCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/stores';
};

export type CreateStoreApiV1StoresPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStoreApiV1StoresPostError = CreateStoreApiV1StoresPostErrors[keyof CreateStoreApiV1StoresPostErrors];

export type CreateStoreApiV1StoresPostResponses = {
    /**
     * Successful Response
     */
    201: StoreResponse;
};

export type CreateStoreApiV1StoresPostResponse = CreateStoreApiV1StoresPostResponses[keyof CreateStoreApiV1StoresPostResponses];

export type GetStoreBySlugApiV1StoresSlugSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/stores/slug/{slug}';
};

export type GetStoreBySlugApiV1StoresSlugSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStoreBySlugApiV1StoresSlugSlugGetError = GetStoreBySlugApiV1StoresSlugSlugGetErrors[keyof GetStoreBySlugApiV1StoresSlugSlugGetErrors];

export type GetStoreBySlugApiV1StoresSlugSlugGetResponses = {
    /**
     * Successful Response
     */
    200: StorePublicResponse;
};

export type GetStoreBySlugApiV1StoresSlugSlugGetResponse = GetStoreBySlugApiV1StoresSlugSlugGetResponses[keyof GetStoreBySlugApiV1StoresSlugSlugGetResponses];

export type GetStoreByIdApiV1StoresStoreIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}';
};

export type GetStoreByIdApiV1StoresStoreIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStoreByIdApiV1StoresStoreIdGetError = GetStoreByIdApiV1StoresStoreIdGetErrors[keyof GetStoreByIdApiV1StoresStoreIdGetErrors];

export type GetStoreByIdApiV1StoresStoreIdGetResponses = {
    /**
     * Successful Response
     */
    200: StoreResponse;
};

export type GetStoreByIdApiV1StoresStoreIdGetResponse = GetStoreByIdApiV1StoresStoreIdGetResponses[keyof GetStoreByIdApiV1StoresStoreIdGetResponses];

export type UpdateStoreApiV1StoresStoreIdPatchData = {
    body: StoreUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}';
};

export type UpdateStoreApiV1StoresStoreIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStoreApiV1StoresStoreIdPatchError = UpdateStoreApiV1StoresStoreIdPatchErrors[keyof UpdateStoreApiV1StoresStoreIdPatchErrors];

export type UpdateStoreApiV1StoresStoreIdPatchResponses = {
    /**
     * Successful Response
     */
    200: StoreResponse;
};

export type UpdateStoreApiV1StoresStoreIdPatchResponse = UpdateStoreApiV1StoresStoreIdPatchResponses[keyof UpdateStoreApiV1StoresStoreIdPatchResponses];

export type GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/onboarding-status';
};

export type GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetError = GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetErrors[keyof GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetErrors];

export type GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetResponses = {
    /**
     * Successful Response
     */
    200: StoreOnboardingStatusResponse;
};

export type GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetResponse = GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetResponses[keyof GetStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusGetResponses];

export type RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/onboarding-status/refresh';
};

export type RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostError = RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostErrors[keyof RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostErrors];

export type RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: StoreOnboardingStatusResponse;
};

export type RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostResponse = RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostResponses[keyof RefreshStoreOnboardingStatusRouteApiV1StoresStoreIdOnboardingStatusRefreshPostResponses];

export type ListCategoriesApiV1StoresStoreIdCategoriesGetData = {
    body?: never;
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: {
        /**
         * Status Filter
         */
        status_filter?: string;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Sort
         */
        sort?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/stores/{store_id}/categories';
};

export type ListCategoriesApiV1StoresStoreIdCategoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCategoriesApiV1StoresStoreIdCategoriesGetError = ListCategoriesApiV1StoresStoreIdCategoriesGetErrors[keyof ListCategoriesApiV1StoresStoreIdCategoriesGetErrors];

export type ListCategoriesApiV1StoresStoreIdCategoriesGetResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPageResponse;
};

export type ListCategoriesApiV1StoresStoreIdCategoriesGetResponse = ListCategoriesApiV1StoresStoreIdCategoriesGetResponses[keyof ListCategoriesApiV1StoresStoreIdCategoriesGetResponses];

export type CreateCategoryApiV1StoresStoreIdCategoriesPostData = {
    body: CategoryCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/categories';
};

export type CreateCategoryApiV1StoresStoreIdCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCategoryApiV1StoresStoreIdCategoriesPostError = CreateCategoryApiV1StoresStoreIdCategoriesPostErrors[keyof CreateCategoryApiV1StoresStoreIdCategoriesPostErrors];

export type CreateCategoryApiV1StoresStoreIdCategoriesPostResponses = {
    /**
     * Successful Response
     */
    201: CategoryResponse;
};

export type CreateCategoryApiV1StoresStoreIdCategoriesPostResponse = CreateCategoryApiV1StoresStoreIdCategoriesPostResponses[keyof CreateCategoryApiV1StoresStoreIdCategoriesPostResponses];

export type DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Category Id
         */
        category_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/categories/{category_id}';
};

export type DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteError = DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteErrors[keyof DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteErrors];

export type DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteResponse = DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteResponses[keyof DeleteCategoryApiV1StoresStoreIdCategoriesCategoryIdDeleteResponses];

export type UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchData = {
    body: CategoryUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Category Id
         */
        category_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/categories/{category_id}';
};

export type UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchError = UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchErrors[keyof UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchErrors];

export type UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CategoryResponse;
};

export type UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchResponse = UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchResponses[keyof UpdateCategoryApiV1StoresStoreIdCategoriesCategoryIdPatchResponses];

export type ListProductsApiV1StoresStoreIdProductsGetData = {
    body?: never;
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: {
        /**
         * Category Id
         */
        category_id?: string | null;
        /**
         * Status Filter
         */
        status_filter?: string;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Sort
         */
        sort?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/stores/{store_id}/products';
};

export type ListProductsApiV1StoresStoreIdProductsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProductsApiV1StoresStoreIdProductsGetError = ListProductsApiV1StoresStoreIdProductsGetErrors[keyof ListProductsApiV1StoresStoreIdProductsGetErrors];

export type ListProductsApiV1StoresStoreIdProductsGetResponses = {
    /**
     * Successful Response
     */
    200: ProductsPageResponse;
};

export type ListProductsApiV1StoresStoreIdProductsGetResponse = ListProductsApiV1StoresStoreIdProductsGetResponses[keyof ListProductsApiV1StoresStoreIdProductsGetResponses];

export type CreateProductApiV1StoresStoreIdProductsPostData = {
    body: ProductCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/products';
};

export type CreateProductApiV1StoresStoreIdProductsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProductApiV1StoresStoreIdProductsPostError = CreateProductApiV1StoresStoreIdProductsPostErrors[keyof CreateProductApiV1StoresStoreIdProductsPostErrors];

export type CreateProductApiV1StoresStoreIdProductsPostResponses = {
    /**
     * Successful Response
     */
    201: ProductResponse;
};

export type CreateProductApiV1StoresStoreIdProductsPostResponse = CreateProductApiV1StoresStoreIdProductsPostResponses[keyof CreateProductApiV1StoresStoreIdProductsPostResponses];

export type DeleteProductApiV1StoresStoreIdProductsProductIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Product Id
         */
        product_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/products/{product_id}';
};

export type DeleteProductApiV1StoresStoreIdProductsProductIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductApiV1StoresStoreIdProductsProductIdDeleteError = DeleteProductApiV1StoresStoreIdProductsProductIdDeleteErrors[keyof DeleteProductApiV1StoresStoreIdProductsProductIdDeleteErrors];

export type DeleteProductApiV1StoresStoreIdProductsProductIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProductApiV1StoresStoreIdProductsProductIdDeleteResponse = DeleteProductApiV1StoresStoreIdProductsProductIdDeleteResponses[keyof DeleteProductApiV1StoresStoreIdProductsProductIdDeleteResponses];

export type GetProductApiV1StoresStoreIdProductsProductIdGetData = {
    body?: never;
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/products/{product_id}';
};

export type GetProductApiV1StoresStoreIdProductsProductIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProductApiV1StoresStoreIdProductsProductIdGetError = GetProductApiV1StoresStoreIdProductsProductIdGetErrors[keyof GetProductApiV1StoresStoreIdProductsProductIdGetErrors];

export type GetProductApiV1StoresStoreIdProductsProductIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProductResponse;
};

export type GetProductApiV1StoresStoreIdProductsProductIdGetResponse = GetProductApiV1StoresStoreIdProductsProductIdGetResponses[keyof GetProductApiV1StoresStoreIdProductsProductIdGetResponses];

export type UpdateProductApiV1StoresStoreIdProductsProductIdPatchData = {
    body: ProductUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Product Id
         */
        product_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/products/{product_id}';
};

export type UpdateProductApiV1StoresStoreIdProductsProductIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProductApiV1StoresStoreIdProductsProductIdPatchError = UpdateProductApiV1StoresStoreIdProductsProductIdPatchErrors[keyof UpdateProductApiV1StoresStoreIdProductsProductIdPatchErrors];

export type UpdateProductApiV1StoresStoreIdProductsProductIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProductResponse;
};

export type UpdateProductApiV1StoresStoreIdProductsProductIdPatchResponse = UpdateProductApiV1StoresStoreIdProductsProductIdPatchResponses[keyof UpdateProductApiV1StoresStoreIdProductsProductIdPatchResponses];

export type ListOrdersApiV1StoresStoreIdOrdersGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Created From
         */
        created_from?: string | null;
        /**
         * Created To
         */
        created_to?: string | null;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Sort
         */
        sort?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/stores/{store_id}/orders';
};

export type ListOrdersApiV1StoresStoreIdOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrdersApiV1StoresStoreIdOrdersGetError = ListOrdersApiV1StoresStoreIdOrdersGetErrors[keyof ListOrdersApiV1StoresStoreIdOrdersGetErrors];

export type ListOrdersApiV1StoresStoreIdOrdersGetResponses = {
    /**
     * Successful Response
     */
    200: OrdersPageResponse;
};

export type ListOrdersApiV1StoresStoreIdOrdersGetResponse = ListOrdersApiV1StoresStoreIdOrdersGetResponses[keyof ListOrdersApiV1StoresStoreIdOrdersGetResponses];

export type CreateOrderApiV1StoresStoreIdOrdersPostData = {
    body: OrderCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/orders';
};

export type CreateOrderApiV1StoresStoreIdOrdersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrderApiV1StoresStoreIdOrdersPostError = CreateOrderApiV1StoresStoreIdOrdersPostErrors[keyof CreateOrderApiV1StoresStoreIdOrdersPostErrors];

export type CreateOrderApiV1StoresStoreIdOrdersPostResponses = {
    /**
     * Successful Response
     */
    201: OrderResponse;
};

export type CreateOrderApiV1StoresStoreIdOrdersPostResponse = CreateOrderApiV1StoresStoreIdOrdersPostResponses[keyof CreateOrderApiV1StoresStoreIdOrdersPostResponses];

export type GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Reference
         */
        reference: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/orders/ref/{reference}';
};

export type GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetError = GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetErrors[keyof GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetErrors];

export type GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetResponses = {
    /**
     * Successful Response
     */
    200: OrderResponse;
};

export type GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetResponse = GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetResponses[keyof GetOrderByReferenceApiV1StoresStoreIdOrdersRefReferenceGetResponses];

export type LookupOrderApiV1StoresStoreIdOrdersLookupPostData = {
    body: OrderLookupRequest;
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/orders/lookup';
};

export type LookupOrderApiV1StoresStoreIdOrdersLookupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LookupOrderApiV1StoresStoreIdOrdersLookupPostError = LookupOrderApiV1StoresStoreIdOrdersLookupPostErrors[keyof LookupOrderApiV1StoresStoreIdOrdersLookupPostErrors];

export type LookupOrderApiV1StoresStoreIdOrdersLookupPostResponses = {
    /**
     * Successful Response
     */
    200: OrderLookupResponse;
};

export type LookupOrderApiV1StoresStoreIdOrdersLookupPostResponse = LookupOrderApiV1StoresStoreIdOrdersLookupPostResponses[keyof LookupOrderApiV1StoresStoreIdOrdersLookupPostResponses];

export type GetOrderApiV1StoresStoreIdOrdersOrderIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: {
        /**
         * Access Token
         */
        access_token?: string | null;
    };
    url: '/api/v1/stores/{store_id}/orders/{order_id}';
};

export type GetOrderApiV1StoresStoreIdOrdersOrderIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrderApiV1StoresStoreIdOrdersOrderIdGetError = GetOrderApiV1StoresStoreIdOrdersOrderIdGetErrors[keyof GetOrderApiV1StoresStoreIdOrdersOrderIdGetErrors];

export type GetOrderApiV1StoresStoreIdOrdersOrderIdGetResponses = {
    /**
     * Successful Response
     */
    200: OrderResponse;
};

export type GetOrderApiV1StoresStoreIdOrdersOrderIdGetResponse = GetOrderApiV1StoresStoreIdOrdersOrderIdGetResponses[keyof GetOrderApiV1StoresStoreIdOrdersOrderIdGetResponses];

export type UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchData = {
    body: OrderStatusUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Order Id
         */
        order_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/orders/{order_id}/status';
};

export type UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchError = UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchErrors[keyof UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchErrors];

export type UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchResponses = {
    /**
     * Successful Response
     */
    200: OrderResponse;
};

export type UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchResponse = UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchResponses[keyof UpdateOrderStatusApiV1StoresStoreIdOrdersOrderIdStatusPatchResponses];

export type UploadMenuApiV1StoresStoreIdMenuImportsUploadPostData = {
    body: BodyUploadMenuApiV1StoresStoreIdMenuImportsUploadPost;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/upload';
};

export type UploadMenuApiV1StoresStoreIdMenuImportsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMenuApiV1StoresStoreIdMenuImportsUploadPostError = UploadMenuApiV1StoresStoreIdMenuImportsUploadPostErrors[keyof UploadMenuApiV1StoresStoreIdMenuImportsUploadPostErrors];

export type UploadMenuApiV1StoresStoreIdMenuImportsUploadPostResponses = {
    /**
     * Successful Response
     */
    201: MenuImportResponse;
};

export type UploadMenuApiV1StoresStoreIdMenuImportsUploadPostResponse = UploadMenuApiV1StoresStoreIdMenuImportsUploadPostResponses[keyof UploadMenuApiV1StoresStoreIdMenuImportsUploadPostResponses];

export type CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostData = {
    body: CreateMenuImportFromUploadRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/from-upload';
};

export type CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostError = CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostErrors[keyof CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostErrors];

export type CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostResponses = {
    /**
     * Successful Response
     */
    201: MenuImportResponse;
};

export type CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostResponse = CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostResponses[keyof CreateMenuImportFromUploadApiV1StoresStoreIdMenuImportsFromUploadPostResponses];

export type ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/{import_id}/process';
};

export type ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostError = ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostErrors[keyof ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostErrors];

export type ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostResponses = {
    /**
     * Successful Response
     */
    200: MenuImportResponse;
};

export type ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostResponse = ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostResponses[keyof ProcessMenuImportApiV1StoresStoreIdMenuImportsImportIdProcessPostResponses];

export type GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/{import_id}';
};

export type GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetError = GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetErrors[keyof GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetErrors];

export type GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetResponses = {
    /**
     * Successful Response
     */
    200: MenuImportResponse;
};

export type GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetResponse = GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetResponses[keyof GetMenuImportApiV1StoresStoreIdMenuImportsImportIdGetResponses];

export type ListMenuImportsApiV1StoresStoreIdMenuImportsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports';
};

export type ListMenuImportsApiV1StoresStoreIdMenuImportsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMenuImportsApiV1StoresStoreIdMenuImportsGetError = ListMenuImportsApiV1StoresStoreIdMenuImportsGetErrors[keyof ListMenuImportsApiV1StoresStoreIdMenuImportsGetErrors];

export type ListMenuImportsApiV1StoresStoreIdMenuImportsGetResponses = {
    /**
     * Response List Menu Imports Api V1 Stores  Store Id  Menu Imports Get
     *
     * Successful Response
     */
    200: Array<MenuImportResponse>;
};

export type ListMenuImportsApiV1StoresStoreIdMenuImportsGetResponse = ListMenuImportsApiV1StoresStoreIdMenuImportsGetResponses[keyof ListMenuImportsApiV1StoresStoreIdMenuImportsGetResponses];

export type UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchData = {
    body: MenuImportItemUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Item Id
         */
        item_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/{import_id}/items/{item_id}';
};

export type UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchError = UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchErrors[keyof UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchErrors];

export type UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: MenuImportResponse;
};

export type UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchResponse = UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchResponses[keyof UpdateImportItemApiV1StoresStoreIdMenuImportsImportIdItemsItemIdPatchResponses];

export type BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchData = {
    body: MenuImportItemsBatchUpdateRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/{import_id}/items:batch';
};

export type BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchError = BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchErrors[keyof BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchErrors];

export type BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchResponses = {
    /**
     * Successful Response
     */
    200: MenuImportResponse;
};

export type BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchResponse = BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchResponses[keyof BatchUpdateImportItemsApiV1StoresStoreIdMenuImportsImportIdItemsBatchPatchResponses];

export type PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/menu-imports/{import_id}/publish';
};

export type PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostError = PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostErrors[keyof PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostErrors];

export type PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostResponses = {
    /**
     * Successful Response
     */
    200: MenuImportResponse;
};

export type PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostResponse = PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostResponses[keyof PublishMenuImportApiV1StoresStoreIdMenuImportsImportIdPublishPostResponses];

export type CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostData = {
    body: UploadIntentCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/uploads/intents';
};

export type CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostError = CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostErrors[keyof CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostErrors];

export type CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostResponses = {
    /**
     * Successful Response
     */
    201: UploadIntentResponse;
};

export type CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostResponse = CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostResponses[keyof CreateUploadIntentApiV1StoresStoreIdUploadsIntentsPostResponses];

export type CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Upload Id
         */
        upload_id: string;
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/uploads/{upload_id}/complete';
};

export type CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostError = CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostErrors[keyof CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostErrors];

export type CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostResponses = {
    /**
     * Successful Response
     */
    200: UploadCompleteResponse;
};

export type CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostResponse = CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostResponses[keyof CompleteUploadApiV1StoresStoreIdUploadsUploadIdCompletePostResponses];

export type OnboardStripeApiV1StoresStoreIdStripeOnboardPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/stripe/onboard';
};

export type OnboardStripeApiV1StoresStoreIdStripeOnboardPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OnboardStripeApiV1StoresStoreIdStripeOnboardPostError = OnboardStripeApiV1StoresStoreIdStripeOnboardPostErrors[keyof OnboardStripeApiV1StoresStoreIdStripeOnboardPostErrors];

export type OnboardStripeApiV1StoresStoreIdStripeOnboardPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StripeStatusApiV1StoresStoreIdStripeStatusGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/stripe/status';
};

export type StripeStatusApiV1StoresStoreIdStripeStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StripeStatusApiV1StoresStoreIdStripeStatusGetError = StripeStatusApiV1StoresStoreIdStripeStatusGetErrors[keyof StripeStatusApiV1StoresStoreIdStripeStatusGetErrors];

export type StripeStatusApiV1StoresStoreIdStripeStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/stripe/login-link';
};

export type StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostError = StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostErrors[keyof StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostErrors];

export type StripeLoginLinkApiV1StoresStoreIdStripeLoginLinkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateIntentApiV1PaymentsCreateIntentPostData = {
    body: CreatePaymentIntentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/payments/create-intent';
};

export type CreateIntentApiV1PaymentsCreateIntentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIntentApiV1PaymentsCreateIntentPostError = CreateIntentApiV1PaymentsCreateIntentPostErrors[keyof CreateIntentApiV1PaymentsCreateIntentPostErrors];

export type CreateIntentApiV1PaymentsCreateIntentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StripeWebhookApiV1WebhooksStripePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/stripe';
};

export type StripeWebhookApiV1WebhooksStripePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListStoreRolesApiV1StoresStoreIdRolesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/roles';
};

export type ListStoreRolesApiV1StoresStoreIdRolesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStoreRolesApiV1StoresStoreIdRolesGetError = ListStoreRolesApiV1StoresStoreIdRolesGetErrors[keyof ListStoreRolesApiV1StoresStoreIdRolesGetErrors];

export type ListStoreRolesApiV1StoresStoreIdRolesGetResponses = {
    /**
     * Response List Store Roles Api V1 Stores  Store Id  Roles Get
     *
     * Successful Response
     */
    200: Array<TeamRoleResponse>;
};

export type ListStoreRolesApiV1StoresStoreIdRolesGetResponse = ListStoreRolesApiV1StoresStoreIdRolesGetResponses[keyof ListStoreRolesApiV1StoresStoreIdRolesGetResponses];

export type CreateStoreRoleApiV1StoresStoreIdRolesPostData = {
    body: TeamRoleCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/roles';
};

export type CreateStoreRoleApiV1StoresStoreIdRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStoreRoleApiV1StoresStoreIdRolesPostError = CreateStoreRoleApiV1StoresStoreIdRolesPostErrors[keyof CreateStoreRoleApiV1StoresStoreIdRolesPostErrors];

export type CreateStoreRoleApiV1StoresStoreIdRolesPostResponses = {
    /**
     * Successful Response
     */
    201: TeamRoleResponse;
};

export type CreateStoreRoleApiV1StoresStoreIdRolesPostResponse = CreateStoreRoleApiV1StoresStoreIdRolesPostResponses[keyof CreateStoreRoleApiV1StoresStoreIdRolesPostResponses];

export type DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/roles/{role_id}';
};

export type DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteError = DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteErrors[keyof DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteErrors];

export type DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteResponse = DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteResponses[keyof DeleteStoreRoleApiV1StoresStoreIdRolesRoleIdDeleteResponses];

export type UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchData = {
    body: TeamRoleUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/roles/{role_id}';
};

export type UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchError = UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchErrors[keyof UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchErrors];

export type UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TeamRoleResponse;
};

export type UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchResponse = UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchResponses[keyof UpdateStoreRoleApiV1StoresStoreIdRolesRoleIdPatchResponses];

export type ListTeamMembersApiV1StoresStoreIdMembersGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/members';
};

export type ListTeamMembersApiV1StoresStoreIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTeamMembersApiV1StoresStoreIdMembersGetError = ListTeamMembersApiV1StoresStoreIdMembersGetErrors[keyof ListTeamMembersApiV1StoresStoreIdMembersGetErrors];

export type ListTeamMembersApiV1StoresStoreIdMembersGetResponses = {
    /**
     * Response List Team Members Api V1 Stores  Store Id  Members Get
     *
     * Successful Response
     */
    200: Array<TeamMemberResponse>;
};

export type ListTeamMembersApiV1StoresStoreIdMembersGetResponse = ListTeamMembersApiV1StoresStoreIdMembersGetResponses[keyof ListTeamMembersApiV1StoresStoreIdMembersGetResponses];

export type UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchData = {
    body: TeamMemberRoleUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/members/{member_id}/role';
};

export type UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchError = UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchErrors[keyof UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchErrors];

export type UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchResponses = {
    /**
     * Successful Response
     */
    200: TeamMemberResponse;
};

export type UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchResponse = UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchResponses[keyof UpdateMemberRoleApiV1StoresStoreIdMembersMemberIdRolePatchResponses];

export type ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostData = {
    body: TeamMemberRoleBulkApplyRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/members/roles/apply';
};

export type ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostError = ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostErrors[keyof ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostErrors];

export type ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostResponses = {
    /**
     * Successful Response
     */
    200: TeamMemberRoleBulkApplyResponse;
};

export type ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostResponse = ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostResponses[keyof ApplyMemberRolesApiV1StoresStoreIdMembersRolesApplyPostResponses];

export type ListStoreInvitesApiV1StoresStoreIdInvitesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/invites';
};

export type ListStoreInvitesApiV1StoresStoreIdInvitesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStoreInvitesApiV1StoresStoreIdInvitesGetError = ListStoreInvitesApiV1StoresStoreIdInvitesGetErrors[keyof ListStoreInvitesApiV1StoresStoreIdInvitesGetErrors];

export type ListStoreInvitesApiV1StoresStoreIdInvitesGetResponses = {
    /**
     * Response List Store Invites Api V1 Stores  Store Id  Invites Get
     *
     * Successful Response
     */
    200: Array<TeamInviteResponse>;
};

export type ListStoreInvitesApiV1StoresStoreIdInvitesGetResponse = ListStoreInvitesApiV1StoresStoreIdInvitesGetResponses[keyof ListStoreInvitesApiV1StoresStoreIdInvitesGetResponses];

export type CreateStoreInviteApiV1StoresStoreIdInvitesPostData = {
    body: TeamInviteCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/invites';
};

export type CreateStoreInviteApiV1StoresStoreIdInvitesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStoreInviteApiV1StoresStoreIdInvitesPostError = CreateStoreInviteApiV1StoresStoreIdInvitesPostErrors[keyof CreateStoreInviteApiV1StoresStoreIdInvitesPostErrors];

export type CreateStoreInviteApiV1StoresStoreIdInvitesPostResponses = {
    /**
     * Successful Response
     */
    201: TeamInviteResponse;
};

export type CreateStoreInviteApiV1StoresStoreIdInvitesPostResponse = CreateStoreInviteApiV1StoresStoreIdInvitesPostResponses[keyof CreateStoreInviteApiV1StoresStoreIdInvitesPostResponses];

export type RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Store Id
         */
        store_id: string;
        /**
         * Invite Id
         */
        invite_id: string;
    };
    query?: never;
    url: '/api/v1/stores/{store_id}/invites/{invite_id}';
};

export type RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteError = RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteErrors[keyof RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteErrors];

export type RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteResponse = RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteResponses[keyof RevokeStoreInviteApiV1StoresStoreIdInvitesInviteIdDeleteResponses];

export type AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/team/invites/accept/{token}';
};

export type AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostError = AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostErrors[keyof AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostErrors];

export type AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostResponses = {
    /**
     * Successful Response
     */
    200: TeamInviteAcceptResponse;
};

export type AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostResponse = AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostResponses[keyof AcceptStoreInviteApiV1TeamInvitesAcceptTokenPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
