"""add_platform_fee_amount_to_orders

Revision ID: 23d79a24529e
Revises: 5c2e0a7f91b4
Create Date: 2026-03-18 16:50:46.337470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d79a24529e'
down_revision: Union[str, None] = '5c2e0a7f91b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('platform_fee_amount', sa.Integer(), nullable=False))
    op.alter_column('store_invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('store_invites', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('uq_store_invites_pending_email'), table_name='store_invites', postgresql_where="(status = 'pending'::invitestatus)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_store_invites_pending_email'), 'store_invites', ['store_id', 'invited_email'], unique=True, postgresql_where="(status = 'pending'::invitestatus)")
    op.alter_column('store_invites', 'accepted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('store_invites', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('orders', 'platform_fee_amount')
    # ### end Alembic commands ###
